# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [5]:
print(np.__version__)
np.show_config()

1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/aarti/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/aarti/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/aarti/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/aarti/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/aarti/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/aarti/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/aarti/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/aarti/anacond

#### 3. Create a null vector of size 10

In [6]:
ze=np.zeros(10)
print(ze)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [7]:
arr=np.array([1,2,3])
print(arr.size * arr.itemsize)

12


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
ze=np.zeros(10)
ze[4]=1
print(ze)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [10]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [11]:
arr=np.arange(1,11)
arr=arr[::-1]
print(arr)

[10  9  8  7  6  5  4  3  2  1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [13]:
n=np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [15]:
i=np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [16]:
r=np.random.random((3,3,3))
print(r)

[[[0.2134937  0.37702801 0.69013767]
  [0.25717746 0.27296818 0.23778824]
  [0.1448179  0.89411198 0.79696346]]

 [[0.14639804 0.75555363 0.10979432]
  [0.24786653 0.42280567 0.15769037]
  [0.92982078 0.43063406 0.38140263]]

 [[0.09967173 0.30379655 0.64142846]
  [0.4266531  0.6231752  0.00297057]
  [0.47319637 0.06259688 0.45040976]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
r=np.random.random((10,10))
print(r)
print(r.min())
print(r.max())

[[0.08986488 0.74613455 0.63935242 0.37983484 0.55123352 0.53770941
  0.62377547 0.28466884 0.0649333  0.94415966]
 [0.90486101 0.37488409 0.47427716 0.98437255 0.50851913 0.42702416
  0.22065877 0.59228162 0.70861009 0.16004747]
 [0.0531373  0.72290243 0.42450245 0.58096719 0.16219529 0.38605903
  0.83980669 0.15984577 0.36429479 0.89582032]
 [0.33979904 0.48626841 0.43467931 0.74869317 0.44382779 0.35865176
  0.8083571  0.89219697 0.99495204 0.31518664]
 [0.94505855 0.27118379 0.27178997 0.67350262 0.35291005 0.56969948
  0.11185808 0.98382252 0.66953706 0.76990277]
 [0.08964794 0.43106169 0.37127225 0.7769619  0.41622618 0.91098725
  0.19582758 0.71703231 0.02389083 0.52686896]
 [0.96000796 0.239339   0.38311224 0.5670318  0.23421014 0.71085508
  0.8185986  0.94396553 0.72675534 0.04185855]
 [0.59388134 0.29755693 0.52237655 0.04895925 0.97589985 0.52799575
  0.70503301 0.63250958 0.32849968 0.35447937]
 [0.44332631 0.17311654 0.2627134  0.35631984 0.81106805 0.57752571
  0.22654824

#### 14. Create a random vector of size 30 and find the mean value

In [21]:
arr=np.random.random(30)
print(arr)
print(arr.mean())

[0.933169   0.18945569 0.26008463 0.37752145 0.52330844 0.44350397
 0.95537565 0.37140414 0.7778099  0.12160308 0.78975012 0.79578608
 0.96109735 0.00828845 0.32765861 0.65021508 0.74279446 0.69963372
 0.40635894 0.02438196 0.86851599 0.23836126 0.19983969 0.41135574
 0.69107596 0.88875994 0.00432054 0.84238599 0.10553736 0.24068385]
0.4950012344896176


#### 15. Create a 2d array with 1 on the border and 0 inside

In [24]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
o = np.ones((5,5))
o = np.pad(o, pad_width=1, mode='constant', constant_values=0)
print(o)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [33]:
arr = np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [36]:
arr = np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [37]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
